SELECT CUSTOMER_NUMBER
FROM (
	SELECT CUSTOMER_NUMBER, 
	RANK() OVER(ORDER BY ORDER_COUNTS DESC) AS RNK
	FROM (
		SELECT CUSTOMER_NUMBER, 
		COUNT(CUSTOMER_NUMBER) AS ORDER_COUNTS
		FROM Orders
		GROUP BY CUSTOMER_NUMBER
	) A
) B
 WHERE RNK  = 1;