SELECT ACTIVITY_DATE AS LOGIN_DATE, COUNT(USER_ID) AS USER_COUNT
FROM  (
    SELECT USER_ID, MIN(ACTIVITY_DATE) ACTIVITY_DATE
    FROM TRAFFIC
    WHERE ACTIVITY = 'LOGIN'
    GROUP BY USER_ID
    HAVING MIN(ACTIVITY_DATE) > DATE_SUB('2019-06-30', INTERVAL 90 DAY)
) T
GROUP BY ACTIVITY_DATE;