SELECT A.STUDENT_ID , A.STUDENT_NAME , B.SUBJECT_NAME, (
    SELECT COUNT(*)
    FROM EXAMINATIONS C
    WHERE A.STUDENT_ID = C.STUDENT_ID
    AND B.SUBJECT_NAME  = C.SUBJECT_NAME) as ATTENDED_EXAMS
FROM STUDENTS  A, SUBJECTS  B
ORDER BY STUDENT_ID, SUBJECT_NAME;