SELECT STOCK_NAME, SUM(CASE WHEN OPERATION = 'BUY' THEN -PRICE WHEN OPERATION = 'SELL' THEN PRICE END) AS CAPITAL_GAIN_LOSS
FROM STOCKS
GROUP BY STOCK_NAME;
/*
각 주식에 대한 자본 손익 반환
자본 손익 - 주식을 사고 판 후의 총 손익
*/