SELECT NAME, BALANCE
FROM USERS U
INNER JOIN (
    SELECT ACCOUNT, SUM(AMOUNT) AS BALANCE
    FROM TRANSACTIONS
    GROUP BY ACCOUNT
    HAVING SUM(AMOUNT) > 10000
) A
ON U.ACCOUNT = A.ACCOUNT;
/*
잔액이 10000원 이상인 계좌 반환
*/