SELECT CONTEST_ID, ROUND(USER_CNT / TOT_CNT * 100, 2) PERCENTAGE
FROM (
    SELECT CONTEST_ID, COUNT(USER_ID) USER_CNT
    FROM REGISTER
    GROUP BY CONTEST_ID
) A, (
    SELECT COUNT(USER_ID) TOT_CNT
    FROM USERS
) B
ORDER BY PERCENTAGE DESC, CONTEST_ID;