SELECT MACHINE_ID,
ROUND((SUM(CASE WHEN ACTIVITY_TYPE='end' THEN TIMESTAMP END) - SUM(CASE WHEN ACTIVITY_TYPE='start' THEN TIMESTAMP END)) / COUNT(DISTINCT PROCESS_ID), 3) PROCESSING_TIME
FROM ACTIVITY
GROUP BY MACHINE_ID;