SELECT E.EMPLOYEE_ID, E.NAME, COUNT(EE.EMPLOYEE_ID) REPORTS_COUNT,
ROUND(AVG(EE.AGE), 0) AVERAGE_AGE
FROM EMPLOYEES E
INNER JOIN EMPLOYEES EE
ON E.EMPLOYEE_ID = EE.REPORTS_TO
GROUP BY E.EMPLOYEE_ID, E.NAME
ORDER BY E.EMPLOYEE_ID;