SELECT ID
FROM (
	SELECT ID, RECORDDATE RD, TEMPERATURE T, LAG(RECORDDATE) OVER (ORDER BY RECORDDATE) PRE_RD, LAG(TEMPERATURE) OVER (ORDER BY RECORDDATE) PRE_T
	FROM WEATHER
) A
WHERE DATE_ADD(PRE_RD, INTERVAL 1 DAY) = RD AND PRE_T < T;