SELECT A.EMPLOYEE_ID
FROM EMPLOYEES A
LEFT OUTER JOIN SALARIES B
ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
WHERE B.EMPLOYEE_ID IS NULL

UNION

SELECT A.EMPLOYEE_ID
FROM SALARIES A
LEFT OUTER JOIN EMPLOYEES B
ON A.EMPLOYEE_ID = B.EMPLOYEE_ID
WHERE B.EMPLOYEE_ID IS NULL
ORDER BY EMPLOYEE_ID;