A = (90, 80)
B = (85, 75)
C = (90, 100)
print(f'1번 학생의 총점은 {sum(A)}점이고, 평균은 {sum(A) / len(A):.1f}입니다.')
print(f'2번 학생의 총점은 {sum(B)}점이고, 평균은 {sum(B) / len(B):.1f}입니다.')
print(f'3번 학생의 총점은 {sum(C)}점이고, 평균은 {sum(C) / len(C):.1f}입니다.')