SELECT PROJECT_ID, EMPLOYEE_ID
FROM (
    SELECT P.PROJECT_ID, P.EMPLOYEE_ID, E.EXPERIENCE_YEARS, RANK() OVER (PARTITION BY P.PROJECT_ID ORDER BY E.EXPERIENCE_YEARS DESC) RNK_YEARS
    FROM PROJECT P
    INNER JOIN EMPLOYEE E
    ON P.EMPLOYEE_ID = E.EMPLOYEE_ID
) A
WHERE RNK_YEARS = 1;