SELECT SS.PRODUCT_ID, SS.YEAR AS FIRST_YEAR, QUANTITY, PRICE
FROM SALES S
INNER JOIN (
    SELECT PRODUCT_ID, MIN(YEAR) YEAR
    FROM SALES
    GROUP BY PRODUCT_ID
) SS
ON S.PRODUCT_ID = SS.PRODUCT_ID AND S.YEAR = SS.YEAR
ORDER BY SS.PRODUCT_ID;