SELECT BOOK_ID, NAME
FROM BOOKS
WHERE BOOK_ID NOT IN (
    SELECT BOOK_ID
    FROM ORDERS
    WHERE DISPATCH_DATE >= '2018-01-01' AND DISPATCH_DATE <= '2018-12-31'
    GROUP BY BOOK_ID
    HAVING SUM(QUANTITY) > 10

    UNION

    SELECT BOOK_ID
    FROM BOOKS
    WHERE DATE_SUB('2019-06-23', INTERVAL 30 DAY) <= AVAILABLE_FROM AND AVAILABLE_FROM <= '2019-06-23'
);