SELECT A.USER_ID AS BUYER_ID, A.JOIN_DATE, IFNULL(AA.ORDERS_IN_2019, 0) AS ORDERS_IN_2019
FROM (
    SELECT USER_ID,
    JOIN_DATE
    FROM USERS
) A
LEFT OUTER JOIN (
    SELECT BUYER_ID,
    COUNT(*) ORDERS_IN_2019
    FROM ORDERS
    WHERE DATE_FORMAT(ORDER_DATE, '%Y') = '2019'
    GROUP BY BUYER_ID
) AA
ON A.USER_ID = AA.BUYER_ID;