SELECT STUDENT_ID, COURSE_ID, GRADE
FROM (
    SELECT STUDENT_ID, COURSE_ID, GRADE, RANK() OVER (PARTITION BY STUDENT_ID ORDER BY GRADE DESC, COURSE_ID) RNK_GRADE
    FROM ENROLLMENTS
) E
WHERE RNK_GRADE = 1
ORDER BY STUDENT_ID;