SELECT RESULTS
FROM (
    SELECT NAME AS RESULTS
    FROM MOVIERATING M
    INNER JOIN USERS U
    ON M.USER_ID = U.USER_ID
    GROUP BY NAME
    ORDER BY COUNT(RATING) DESC, NAME LIMIT 1
) A

UNION ALL

SELECT *
FROM (
    SELECT TITLE AS RESULTS
    FROM MOVIERATING M
    INNER JOIN MOVIES MM
    ON M.MOVIE_ID = MM.MOVIE_ID
    WHERE DATE_FORMAT(CREATED_AT, '%Y-%m') = '2020-02'
    GROUP BY TITLE
    ORDER BY AVG(RATING) DESC, TITLE LIMIT 1
) B;