SELECT DISTINCT A.VISITED_ON, (
    SELECT SUM(B.AMOUNT) SUM_AMOUNT
    FROM CUSTOMER AS B
    WHERE DATEDIFF(A.VISITED_ON, B.VISITED_ON) BETWEEN 0 AND 6
) AS AMOUNT, ROUND ((
    SELECT SUM(B.AMOUNT) / 7 AS AVERAGE_AMOUNT
    FROM CUSTOMER AS B
    WHERE DATEDIFF(A.VISITED_ON, B.VISITED_ON) BETWEEN 0 AND 6), 2
) AS AVERAGE_AMOUNT
FROM CUSTOMER AS A
WHERE DATEDIFF(A.VISITED_ON, (SELECT MIN(VISITED_ON) FROM CUSTOMER)) >= 6
ORDER BY A.VISITED_ON;