SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
FROM DEPARTMENT D
INNER JOIN (
    SELECT DEPARTMENTID, NAME, SALARY, RANK() OVER (PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) SAL_RANK
    FROM EMPLOYEE
) E
ON E.DEPARTMENTID = D.ID
WHERE E.SAL_RANK = 1;