SELECT S.USER_ID, IFNULL(CONFIRMATION_RATE, 0) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT OUTER JOIN (
    SELECT USER_ID, ROUND(COUNT(CASE WHEN ACTION = 'CONFIRMED' THEN 1 END) / COUNT(*), 2) AS CONFIRMATION_RATE
    FROM CONFIRMATIONS
    GROUP BY USER_ID
) C
ON S.USER_ID = C.USER_ID;