SELECT ROUND(COUNT(PLAYER_ID) / (SELECT COUNT(DISTINCT PLAYER_ID) TOT_CNT FROM ACTIVITY), 2) FRACTION
FROM (
    SELECT PLAYER_ID, EVENT_DATE, RANK() OVER (PARTITION BY PLAYER_ID ORDER BY EVENT_DATE) RNK_DATE, LAG(PLAYER_ID) OVER (ORDER BY PLAYER_ID, EVENT_DATE) PREV_ID, LAG(EVENT_DATE) OVER (ORDER BY PLAYER_ID, EVENT_DATE) PREV_DATE
    FROM ACTIVITY
) A
WHERE RNK_DATE = 2 AND DATE_SUB(EVENT_DATE, INTERVAL 1 DAY) = PREV_DATE AND PLAYER_ID = PREV_ID;