SELECT QUESTION_ID
FROM (
    SELECT QUESTION_ID, COUNT(CASE WHEN ACTION = 'ANSWER' THEN 1 END) / COUNT(CASE WHEN ACTION = 'SHOW' THEN 1 END) RATIO
    FROM SURVEY
    GROUP BY QUESTION_ID
) A
ORDER BY RATIO DESC LIMIT 1;