SELECT C.NAME
FROM CANDIDATE C
INNER JOIN VOTE V
ON C.ID = V.CANDIDATEID
GROUP BY C.NAME
HAVING COUNT(V.CANDIDATEID) = (
    SELECT MAX(CNT)
    FROM (SELECT COUNT(CANDIDATEID) CNT FROM VOTE GROUP BY CANDIDATEID) A
);