SELECT D.DEPT_NAME, IFNULL(S.STUDENT_CNT, 0) STUDENT_NUMBER
FROM DEPARTMENT D
LEFT OUTER JOIN (
    SELECT COUNT(STUDENT_ID) STUDENT_CNT, DEPT_ID
    FROM STUDENT
    GROUP BY DEPT_ID
) S
ON D.DEPT_ID = S.DEPT_ID;